config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  namespace :instructor do
    resources :courses, only: [:new, :create, :show]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
    <%= link_to course.title, course_path(course) %></h2>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 text-center">
        <%= link_to 'More details. . . ', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr">
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Admin functions', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %> 
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit 'Create', class: 'btn-btn-primary' %>
    <br />
  <% end %>
  <br />  
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @course.title %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='flex-content-container'>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Flixter', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class='navbar-nav'>
            <% if user_signed_in? %>
              <li class='nav-item'>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
        <% if notice.present? %>
          <p class='alert alert-info'><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class='alert alert-danger'><%= alert %></p>
        <% end %>
      <%= yield %>
    </div>

    <div id='footer'>
      <div class='container'>
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach A Course', new_instructor_course_path %>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class='hero'>
  <br />
  <div class='frosty col-10 offset-1 text-center'>
    <br />
    <h1>Learn magic from the pros</h1>
    <br />
    <h2>I'm an illusionist, Bill</h2>
    <br />
    <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
    <br /><br />
  </div>
</div>

<br />
<div class='row feature text-center'>
  <div class='col-12 col-sm'>
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with awesome teachers.</p>
  </div>
  <div class='col-12 col-sm'>
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a course archive of lessons.</p>
  </div>
  <div class='col12 col-sm'>
    <h3>Join The Community</h3>
    <br />
    <p>Learn with a group of like-minded individuals.</p>
  </div>
</div>